name: recovery_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  file_picker:
  camera: ^0.10.5+5
  path_provider:
  flutter_otp_text_field: ^1.1.1
  permission_handler:
  geolocator: ^10.1.0
  rename: ^3.0.1
  xml: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  dio: ^5.4.0
  font_awesome_flutter: ^10.6.0
  delightful_toast: ^1.1.0
  image_picker: ^0.8.9
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.3
  sim_card_info:
    git:
      url: https://github.com/safvan-husain/sim_card_info.git
      ref: 8e9b6b09beea6da1314be9be84bf921e082dc991
  image_gallery_saver: ^2.0.3
  device_imei: ^0.0.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
